name: Build SecureBoot Binaries

on:
  workflow_call:


jobs:
  build:
    name: Build

    runs-on: ubuntu-latest

    steps:
    - name: Checkout Self
      uses: actions/checkout@v3
    
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: 3.11
        cache: 'pip'
    
    - name: Install Pip Dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Run Ruff Checks
      run: ruff check scripts --format=github

    - name: Build Intel / ARM Binaries
      run: python scripts/secure_boot_default_keys.py --keystore keystore/keystore.toml -o Artifacts
    
    - name: Upload Binaries as Artifact
      uses: actions/upload-artifact@v3
      with:
        name: Binaries
        path: Artifacts/
    
    - name: Prepare Release Artifacts
      run: python scripts/prepare.py Artifacts --output ReleaseArtifacts --version ${{ github.event.release.tag_name }}
      if: startsWith(github.ref, 'refs/tags/')
    
    - name: Upload Release Artifacts
      uses: softprops/action-gh-release@v1
      if: startsWith(github.ref, 'refs/tags/')
      with:
        files: ReleaseArtifacts/*
        