# This workflow verifies the python scripts and that the binary blobs
# can be successfully built.
#
# Copyright (c) Microsoft Corporation.
# SPDX-License-Identifier: BSD-2-Clause-Patent

name: PR Check

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    name: Build Binaries
    uses: ./.github/workflows/BuildBinaries.yml
  
